---
title: "Viz part 1"
output: github_document
date: "2023-09-28"
---
```{r}
## R Markdown
library(ggridges)
library(tidyverse)
```


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```

## Fancy plot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + geom_point(aes(color = name))
```

## Plot with smooth line

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  geom_smooth(se = FALSE)
```

## Plot with facets

```{r}
ggplot (weather_df, aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  geom_smooth() +
  facet_grid(. ~ name)
```

## Trying a different plot

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = .3) + 
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```

```{r}
ggplot(weather_df, aes(x = tmax, y = tmin)) + 
  geom_hex()
  
```

## Univariate plotting

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) +
  geom_histogram(position = "dodge")
```

## Let's use a density plot

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) +
  geom_density(alpha = .3, adjust = .75)
```

## Using boxplots

```{r}
ggplot(weather_df, aes(y = tmax, x = name)) +
  geom_boxplot()
```

## Violin plots?

```{r}
ggplot(weather_df, aes(y = tmax, x = name)) +
  geom_violin()
```

## Ridge plot

```{r}
ggplot(weather_df, aes(x = tmax, y = name)) +
  geom_density_ridges()
```


```{r}
ggplot(weather_df, aes(x = date, y = tmax)) +
  geom_line(alpha = .5) +
  geom_point(size = .5)
```

```{r}
ggp_weather = 
  ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) 

ggsave("ggp_weather.pdf", ggp_weather, width = 8, height = 5)
```

```{r, fig.width=6, fig.height=.6}
ggp_weather
```




